// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Prisma's migrate engine requires the "postgresql://" scheme.
// Supabase and some PaaS providers supply "postgres://" — normalise it here.
function migrateUrl(): string {
  const raw = process.env["DATABASE_URL"] ?? "";
  return raw.replace(/^postgres:\/\//, "postgresql://");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: migrateUrl(),
  },
});
